# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20170227_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
    ]
