# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20170227_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='MUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mus', models.FileField(upload_to='Music')),
            ],
        ),
    ]
